language: node_js

node_js: '6'

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
    - os: osx
      osx_image: xcode7.2

      

install:
- npm install
script:
- npm test

