language: node_js

node_js: '6'

matrix:
  include:
    - os: linux
      dist: trusty
      sudo: required
      env: TEST_SUITES=UNIT_TEST

      
before_install:
- chmod +x ./scripts/*.sh

script:
- ls -ltrhaZ ios
- ls -ltrhaZ ios/build
- ls -ltrhaZ /Users/travis/build/fyhao/react-native-wf/ios/
- ls -ltrhaZ /Users/travis/build/fyhao/react-native-wf/ios/build
